version: "3"

services:
  mysql:
    platform: linux/arm64
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    # mysqlの履歴を残す
    volumes:
      - ./data:/var/lib/mysql